### ISSUE TITLE
`e2e-tests` failing

### ISSUE THREAD

**Issue by muddlebee** [paritytech/asset-transfer-api#482]
attaching logs below after running

> yarn test:e2e

```
2024-12-13 18:04:14        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32603: Internal RpcError: -32008: Response is too big: Exceeded max limit of 4194304
2024-12-13 18:04:14        API/INIT: Error: FATAL: Unable to initialize the API: -32603: Internal RpcError: -32008: Response is too big: Exceeded max limit of 4194304
    at ApiPromise.__internal__onProviderConnect (file:///C:/Users/91824/Documents/Codes/swush-me/asset-transfer-api/node_modules/@polkadot/api/base/Init.js:383:27)   
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

[18:04:14.056] ERROR (ws): Error handling request: 'RpcError: -32008: Response is too big: Exceeded max limit of 4194304
    at checkError (file:///C:/Users/91824/Documents/Codes/swush-me/asset-transfer-api/node_modules/@polkadot/rpc-provider/coder/index.js:19:15)
    at RpcCoder.decodeResponse (file:///C:/Users/91824/Documents/Codes/swush-me/asset-transfer-api/node_modules/@polkadot/rpc-provider/coder/index.js:35:9)
    at WsProvider.__internal__onSocketMessageResult (file:///C:/Users/91824/Documents/Codes/swush-me/asset-transfer-api/node_modules/@polkadot/rpc-provider/ws/index.js:414:51)
    at WebSocket.__internal__onSocketMessage (file:///C:/Users/91824/Documents/Codes/swush-me/asset-transfer-api/node_modules/@polkadot/rpc-provider/ws/index.js:403:20)
    at callListener (C:\Users\91824\Documents\Codes\swush-me\asset-transfer-api\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\91824\Documents\Codes\swush-me\asset-transfer-api\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at Receiver.receiverOnMessage (C:\Users\91824\Documents\Codes\swush-me\asset-transfer-api\node_modules\ws\lib\websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)'
    app: "chopsticks"
 ❯ |e2e| e2e-tests/polkadotAssetHub.hydration.spec.ts (7)
   ❯ Polkadot AssetHub <> Hydration (7)
     ✓ AssetHub Local DOT Transfer 36245ms
     × AssetHub Local Pool Asset Transfer 200029ms
       - [ beforeEach ]
       | [ afterEach ]
     × Hydration Local HDX Transfer 200020ms
       | [ beforeEach ]
       \ [ afterEach ]
     \ Transfer DOT From Hydration to AssetHub
       \ [ beforeEach ]
     · Transfer DOT From AssetHub to Hydration
     · Transfer SnowBridge WETH From Hydration To AssetHub
     · Transfer SnowBridge WETH From AssetHub To Hydration
 ❯ |e2e| e2e-tests/moonbeam.hydration.spec.ts (2) 234285ms
   ❯ Moonbeam <> Hydration (2) 234284ms
     × Transfer GLMR from Moonbeam to Hydration 115414ms
     ✓ Transfer HDX from Hydration to Moonbeam 118867ms
 ❯ |e2e| e2e-tests/polkadotAssetHub.bridgeHub.spec.ts (1) 200164ms
   ❯ Polkadot AssetHub <> Ethereum (1) 200163ms
     × Snowbridge WETH From AssetHub to Ethereum 200161ms
       \ [ beforeEach ]
       - [ afterEach ]



```

**Comment by muddlebee** [comment]
I took the latest pull and all dependencies are upto date.
